hngprojects/AI-Ad-Gen-Frontend

src/app/ad-form/_components/image-ad-form.tsx
src/app/ad-type/ad-type-selector.tsx
src/app/constants/step-one-form-options.ts
src/app/layout.tsx

Enhancements to Image Ad Form UI & Ad Type Selection
This update improves the UI of the image-ad-form.tsx and ad-type-selector.tsx components for a more polished user experience. Key changes include:
-Refined the layout and styling for better responsiveness and aesthetics.
-Disabled the Video Ad option, allowing only Image Ad selection to proceed.
-Adjusted spacing, colors, and button states for a more intuitive flow.
-These changes enhance usability while ensuring a seamless ad creation process.

Enhancement to Image Ad Form UI and Restriction of Ad Type Selection

---

src/app/(adgen)/container.tsx
src/app/(adgen)/create-ad/(formGroup)/ad-form/page.tsx
src/app/sections/header.tsx

Fixed deployment error while running "pnpm build"

fix: deployment fixes

---

package.json
pnpm-lock.yaml
src/components/ui/ReusableMultiselect.tsx
src/components/ui/checkbox.tsx
src/components/ui/multi-select.tsx

Fixed the multi select component.

Fix: Multi-select

---

.github/workflows/frontend-cicd.yml

We were facing billing issues with the github runner, so we're switching to the self-hosted one

fix: change runner to self hosted runner

---

src/app/(adgen)/create-ad/(formGroup)/preview/_components/single-image-preview.tsx

changed image preview grid to single image

fix: changed image preview grid to single image

---

src/app/sections/createAD.tsx
src/app/sections/hero.tsx

Feature: Changed the generate form route.

feat: changed the generate form route

---

.env.example
.gitignore
next.config.ts
src/app/(adgen)/create-ad/(formGroup)/ad-form/_components/image-ad-form.tsx
src/app/(adgen)/create-ad/(formGroup)/preview/[imageId]/page.tsx
src/app/(adgen)/create-ad/(formGroup)/preview/_components/single-image-preview.tsx
src/hooks/use-image-ad.ts
src/lib/api.ts
src/types/index.ts

created api instance for post request and get request

feature: Added API integration and image preview functionality for image ad generation

---

src/app/(adgen)/create-ad/(formGroup)/ad-form/_components/image-ad-form.tsx
src/app/(adgen)/create-ad/(formGroup)/preview/_components/single-image-preview.tsx
src/components/ui/loader.tsx
src/hooks/use-image-ad.ts
src/lib/api.ts

Remove console log statements for cleaner code and improved performance

Feature: Remove console log statements for cleaner code and improved performance

---

next.config.ts
src/app/(adgen)/components/ad-type.tsx
src/app/(adgen)/create-ad/(formGroup)/preview/[imageId]/page.tsx
src/app/(adgen)/create-ad/(formGroup)/preview/_components/single-image-preview.tsx
src/app/(adgen)/create-ad/ad-type/ad-type-selector.tsx
src/components/ad-preview-navigation.tsx
src/hooks/use-image-ad.ts
src/types/index.ts

feat: enhance image handling and loading states in ad generation flow

feat: refactor api logic and fetch image from the endpoint

---

src/app/(adgen)/create-ad/(formGroup)/ad-form/_components/image-ad-form.tsx
src/app/constants/step-one-form-options.ts

-Fixed Client side 422 error by mapping correct values to match the backend payload.

fixed form error 422:client side error

---

src/domains/external/components/create-ad.tsx

-Fixed punctuation in the create ad component.

Enhanced UI by adding punctuations to the Create ad component

---

package.json
pnpm-lock.yaml
src/app/(external)/(adgen)/create-ad/(formGroup)/preview/[imageId]/page.tsx
src/domains/ads-gen/api/use-submit-campaign.ts
src/domains/ads-gen/components/image-ad-form.tsx
src/domains/ads-gen/components/single-image-preview.tsx
src/domains/external/components/desktop-ad-preview-navigation.tsx
src/domains/external/components/mobile-generate-button.tsx
src/lib/sonner/sonner-toaster.tsx
src/schemas/ad-schema.ts
src/types/index.ts

image not showing on preview fix

fix: image not showing on preview fix

---

src/app/(external)/(adgen)/create-ad/(formGroup)/preview/[imageId]/page.tsx
src/domains/external/components/desktop-ad-preview-navigation.tsx

User can now download their images in PNG and JPEG format.

feat: download feature

---

src/domains/ads-gen/components/image-ad-form.tsx

Reverts hngprojects/AI-Ad-Gen-Frontend#93

Revert "fix: fix popup showing when limit is still available in v1.2"

---

src/domains/ads-gen/components/image-ad-form.tsx
src/domains/external/components/header.tsx

Commented out components for version 1.3

revert: remove version 1.3

---

src/domains/ads-gen/utils/step-one-form-options.ts

PR Title:
fix: Resolve 422 Status Error from AD Group Value
Description:
This PR fixes the 422 Unprocessable Entity error occurring due to unexpected character in an AD Group value.

fix: remove unwanted charcter in ad-group select value

---

src/app/not-found.tsx

**Tittle:**
Fixed icon on "not-found" page.
**Description:**
Replaced non-functional svg icon with icon from Lucide-react.

feat: update NotFound component to use MoveRight icon

---

src/app/not-found.tsx

Fixed the arrow-right svg icon on the not-found page.

Not found Right Arrow

---

src/app/(auth)/signin/sign-in-form.tsx
src/domains/external/components/create-ad.tsx

-The /signup page was not responsive for mobile screens, caused major cut outs.
-the signup page has been fixed.

fix: Updated responsiveness on mobile screens to prevent cutout

---

src/app/(auth)/signin/sign-in-form.tsx
src/domains/auth/components/AuthNav.tsx
src/domains/external/components/desktop-ad-preview-navigation.tsx

…n for the preview page for this first version

feat: used app router logo inport and aldo comment out download button for the preview page for this first version

---

src/app/(auth)/auth/callback/auth-callback.tsx
src/app/(auth)/components/protected-route.tsx
src/app/(external)/(dashboard)/components/image-ad-form.tsx
src/app/(external)/(dashboard)/dashboard/page.tsx
src/lib/api.ts
src/store/auth-store.ts

**Title:**
Persist auth status/Fixed ad
**Description:**
Stored token and refactored the image generation api consumption

Fix:token persistance/Image generation

---

.github/workflows/frontend-cicd.yml

chore: add env variables

---

.github/workflows/frontend-cicd.yml

chore: add public folder

---

src/app/(external)/(dashboard)/components/dashboard-hero.tsx
src/app/(external)/(dashboard)/dashboard/page.tsx

-Fixed the dashboard layout to match new UI designs.

fix:redesigned dashboard layout to fit new design

---

src/app/(marketing)/phase-one/page.tsx
src/domains/external/components/access.tsx
src/domains/external/components/heromarketing.tsx
src/domains/external/components/heromarketing2.tsx

-Create Standalone pages for marketing purposes.
-Make both pages responsive.
-prevent laptop image cutout on mobile screens.

feat:create standalone pages for marketing purpose

---

src/domains/external/components/desktop-ad-preview-navigation.tsx

fix: replace standalone image url

---

src/app/(external)/(adgen)/create-ad/(formGroup)/preview/[imageId]/page.tsx
src/app/(external)/(dashboard)/components/image-ad-form.tsx
src/domains/external/components/desktop-ad-preview-navigation.tsx
src/domains/external/components/share-modal.tsx

Test social media sharing

---

src/app/(other-externals)/features/page.tsx

TL:DR
Added a hover effect to the button for better user feedback and interactivity

feat: Add hover effect to get started now button for improved interactivity

---

src/domains/external/components/header.tsx

feat: remonve extra signin button

---

src/app/(external)/(landing)/page.tsx
src/app/(other-externals)/blogs/[blogId]/page.tsx
src/domains/external/components/create-ads.tsx
src/domains/external/components/heromarketing2.tsx

Reverts hngprojects/AI-Ad-Gen-Frontend#282

Revert "Correct some copies on the landing pages"

---

src/domains/auth/components/AuthFooter.tsx
src/domains/external/components/header.tsx

feat: add contact us menu to navbar and update auth footer

---

src/app/(other-externals)/components/onboarding-step.tsx

-Fixed the transition delay time for images.

fix:reduce transition delay duration for images-how-it-works-page

---

src/app/(marketing)/create-video-ads/layout.tsx
src/app/(marketing)/phase-two/layout.tsx
src/app/(other-externals)/components/blog-footer.tsx
src/app/(other-externals)/components/blogs-header.tsx
src/components/icons/icon.tsx

Updated header and footer components

Components: Updated header and footer components

---

src/app/(external)/(other-externals)/about-us/page.tsx
src/app/layout.tsx
src/components/icons/icon.tsx
src/domains/other-externals/components/blog-footer.tsx
src/domains/other-externals/components/blogs-header.tsx

- changed entire app background color to white
- footer responsive and slight fixes

fix: footer responsiveness and link check- changed bg-color of entire app

---

src/domains/ads-gen/components/avatar.tsx

Update profile dropdown

---

src/app/(external)/(dashboard)/components/image-ad-form.tsx
src/domains/ads-gen/api/ad-image-generate.ts

feat: Enhance ad image generation with completed data handling and im…proved response checks

feat: fixed the share image for the stand alone page preview DONE

---

src/app/(external)/(dashboard)/components/image-ad-form.tsx

**CHanges**
- Changed the input border to match the design
- Modified the input placeholder styles

Fix/input UI fixes

---

src/domains/external/components/desktop-ad-preview-navigation.tsx

feat: add save and exit button to community page

---

src/app/(auth)/signin/sign-in-form.tsx

feat: add back navigation link and logo to sign-in form

---

src/domains/external/components/gallery.tsx

feat: add new background image to gallery in home page

---

src/app/(external)/(dashboard)/components/image-ad-form.tsx
src/domains/ads-gen/api/use-image-paint.ts

Reverts hngprojects/AI-Ad-Gen-Frontend#407

Revert "Feat: enhance image inpainting functionality with loading indicators and progress tracking"

---

src/app/(external)/(dashboard)/dashboard/profile/page.tsx
src/hooks/use-subscription-status.ts
src/store/auth-store.ts

Refactored API calls to use the modified endpoints. "/api/v1/subscriptions/me", "/api/v1/subscriptions/me", "/api/v1/users/{user_id}"
Modified data types

refactor: update API calls for user and subscription status

---

src/app/(external)/(other-externals)/(marketing)/ai-creative/page.tsx
src/app/(external)/(other-externals)/(marketing)/ai-marketing/page.tsx
src/domains/external/components/ai-creative-create-ad.tsx

Replaced sections in the marketing pages that were used in the homepage

feat: update section in ai creative and ai marketing pages

---

src/components/ui/pagination.tsx
src/domains/ads-gen/api/use-ads-data.ts
src/domains/ads-gen/components/dashboard-content.tsx
src/domains/external/components/hero.tsx

Add a seamless pagination controller

Dashboard pagination

---

src/app/(external)/(dashboard)/components/image-ad-form.tsx
src/components/ui/image-editor.tsx
src/domains/ads-gen/api/ad-image-generate.ts
src/domains/ads-gen/components/dashboard-content.tsx
src/domains/external/components/image-selector.tsx
src/store/inpaint-store.ts

**Features**
- Consumed the "/inpaint" endpoint
- Initialized "inpaint" zustand store
- Parsed inpaint data to UI to replace generated image

feat: implement inpainting store and update image editor component

---

src/app/(external)/(dashboard)/dashboard/profile/page.tsx
src/app/(external)/(other-externals)/pricing/page.tsx
src/app/(external)/(other-externals)/privacy-policy/page.tsx
src/app/not-found.tsx
src/domains/external/components/earlyaccess.tsx
src/lib/react-query/query-provider.tsx

Fix : 
https://linear.app/unique-gift/issue/GENFE-21/validation-error-displays-after-submitting-form-details-on-external
https://linear.app/unique-gift/issue/GENFE-27/try-for-free-button-redirects-to-landing-page-instead-of-sign-up-page
https://linear.app/unique-gift/issue/GENFE-28/incorrect-contact-email-on-privacy-policy-page
https://linear.app/unique-gift/issue/GENFE-30/misaligned-text-on-user-profile-page

Genfe 21 27 28 30

---

src/app/(external)/(dashboard)/dashboard/profile/page.tsx
src/domains/external/components/header.tsx
src/store/auth-store.ts

refactor: update subscription data structure and adjust related components to mattch endpoint respose

---

package.json
pnpm-lock.yaml
src/components/ui/control-panel.tsx
src/components/ui/tooltip.tsx

feat: add tooltip to text control panel

---

src/app/(external)/(dashboard)/components/image-ad-form.tsx

feat: update ui for form inputs and flow for image genaration

---

.github/workflows/frontend-cicd.yml

- Replaced hardcoded deployment port, name, and directory with GitHub Actions variables.
- Ensures cleaner config and easier updates via repo settings.
- Separated variables for prod (main) and staging (dev) branches.

chore: switch deployment config to use GitHub Actions variables.

---

src/app/(dashboard)/components/image-ad-form.tsx
src/domains/external/components/share-modal.tsx

Fix BUG 001 & BUG 004 
from the [sheet](https://docs.google.com/spreadsheets/d/14b2wNv9wyT2GtOycsCcB365TvLm0hZRayr9Xg0Msx44/edit?gid=871708483#gid=871708483).

fix : The Ad title being populated in the Target Audience  input field, change sharing label 'twitter' to 'X'
